name: "Build and Deploy"
on:
  push:
    branches:
    - main
    - master
    paths-ignore:
    - .gitignore
    - README.md
    - LICENSE

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  generate:
    runs-on: ubuntu-latest
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Setup Pages
      id: pages
      uses: actions/configure-pages@v4

    - name: Prepare cppwp
      run: |
        cd cppwp
        mkdir c++
        mv *.* c++

    - name: Copy standards
      run: |
        mkdir build
        cp -r cppwp/c++ build/c++
        cp -r cppwp/n3337 build/c++11
        cp -r cppwp/n4140 build/c++14
        cp -r cppwp/n4659 build/c++17
        cp -r cppwp/n4861 build/c++20
        cp -r cppwp/n4950 build/c++23

    - name: Copy index
      run: |
        mkdir -p build
        cp index.html build/index.html

    - name: Test site
      run: |
        if [ ! -f build/c++/intro.html ]
        then
        echo "Generating files failed."
        exit 1
        fi

    - name: Upload site artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
